### ISSUE TITLE
error during installation 

### ISSUE THREAD

**Issue by becology1100** [wshurafa/laravel-payfort#1]
[InvalidArgumentException]
  Could not find package wshurafa/laravel-payfort at any version for your min
  imum-stability (stable). Check the package spelling or your minimum-stabili
  ty

**Comment by wshurafa** [comment]
This package is in early production stages, so if you want to use this package make sure not to use it directly in a production project. 
If this Ok with you, in your project's composer.json file change minimum-stability to dev or add this option in the root of the file.
