### ISSUE TITLE
I am trying to install payfort payment gateway wshurafa/laravel-payfort in laravel 5.4 version giving error

### ISSUE THREAD

**Issue by gopinadh03** [wshurafa/laravel-payfort#2]
Please help me I am trying to use payfort in my laravel(5.4) application using composer command "composer require wshurafa/laravel-payfort ". But it is giving fallowing error message. 

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest]
 [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--
ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|
--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<
packages>]...

**Comment by wshurafa** [comment]
This package is in early production stages, so if you want to use this package make sure not to use it directly in a production project.
If this Ok with you, in your project's composer.json file change minimum-stability to dev or add this option in the root of the file.
