### ISSUE TITLE
response view

### ISSUE THREAD

**Issue by reshma-r-p** [wshurafa/laravel-payfort#5]
My application is in Laravel 5.1.  Iam using a this library for integrating it. When i am using purchase request api, it returns a html page.   When i check it in postman, for pretty, got a html response. But for preview, i got a blank page. What should i do? I couldnt proceed without getting that preview

**Comment by wshurafa** [comment]
This page includes an auto submit form, if you've disabled javascript on your browser it won't work. Make sure javascript works and try again.

**Comment by reshma-r-p** [comment]
But i  checkd it in postman. It return the form. When i click the preview option it shows only the blank page

**Comment by wshurafa** [comment]
Yes, you are completely right, all form inputs are hidden. Thus you will not see any thing.

**Comment by reshma-r-p** [comment]
actually i am wokring on api side. So if am using this what response should i give to app team. And how can i check it?

**Comment by wshurafa** [comment]
If you are developing an API for native mobile apps, it is better to use payfort mobile SDK. You can check about payfort mobile SDK [here](https://docs.payfort.com/docs/mobile-sdk/build/index.html).

But if you are using cross platform for mobile development, the mobile side should display the returning (html page) in a web view and then allow the user to make the order payment.

**Comment by reshma-r-p** [comment]
yeah we are using cross platform. So i just need to pass this data to them? huh? But the thing is all input is hidden then how can they load this response in web view?

**Comment by wshurafa** [comment]
You can find that the form is autosubmitted on page load 
`document.frm.submit();`
So once the page is loaded this form will autosubmit to payfort, and payfort will display the payment page.
So you can safely pass this response to mobile side, and they should display it in web view, and the procedure should go then.

**Comment by reshma-r-p** [comment]
ok. Is there any way to check this from server side?

**Comment by wshurafa** [comment]
What do you want to check about it ?

**Comment by reshma-r-p** [comment]
the redirection page and payment thing.

**Comment by wshurafa** [comment]
You can request the page on your local machine, and view the payment page.

**Comment by reshma-r-p** [comment]
i have tried it in my local page still it getting only the blank page. And i checked whether js is enabled or not. Its enabled. No redirection happening. Only the blank page

**Comment by reshma-r-p** [comment]
i have tried it in my local page still it getting only the blank page. And
i checked whether js is enabled or not. Its enabled. No redirection
happening. Only the blank page

**Comment by wshurafa** [comment]
Ok, I'll do a quick fix to add a visual button to click on if no redirection occured

**Comment by reshma-r-p** [comment]
Ok... Thanks.

**Comment by wshurafa** [comment]
Do composer update and try again

**Comment by reshma-r-p** [comment]
Ok i will try

**Comment by reshma-r-p** [comment]
Now i got this error

Error code: 00013 
Error Message: Invalid Currency
My currency type is AED

**Comment by wshurafa** [comment]
This is totally a payfort and account issue, your account must be allowed to use this currency

**Comment by reshma-r-p** [comment]
I think my account is allowed to use this currency.

**Comment by wshurafa** [comment]
Ok, anyway this is a payfort error message and you can check with payfort regarding that.
make sure that there is not space or other character in your value.

**Comment by reshma-r-p** [comment]
Ok, Thanks for your support :)
