### ISSUE TITLE
How can i check response matches SHA Response Phrase

### ISSUE THREAD

**Issue by reshma-r-p** [wshurafa/laravel-payfort#9]
I need to check whether the response from the payfort matches the SHA Response Phrase in my env settings. How can i done that?

**Comment by wshurafa** [comment]
You can check the following line which make the signature check for each payfort response:
https://github.com/wshurafa/laravel-payfort/blob/master/src/Traits/PayfortAPIRequest.php#L160

**Comment by reshma-r-p** [comment]
Thanks.
But in that one i couldn't check it in return url by using type = 'response'

for that i added following code snippet in your library. 

**Location :  wshurafa/laravel-payfort/src/Traits/PayfortRedirectRequest.php**

    public function checkSignatureValid($requestParams,$response){
        return $this->calcPayfortSignature($requestParams, $response);
    }

In return url i have added following lines,

    $params = Input::all();
    $signature = (Payfort::redirection()->checkSignatureValid($params,'response'));
        if($signature != $params['signature']){
            return 'error';
        }

**Comment by reshma-r-p** [comment]
And one more thing. Is any method available to revert my payment..?

**Comment by wshurafa** [comment]
You don't have to pass the request, it's only required parameters and params type weather it is a request to or response from payfort.

So you can call the calc signature Payfort::redirection()->calcPayfortSignature($params,'response') and then throw exception if signature is mismatched.

About refunding payment, I'm working on it and I'll publish it once done.

**Comment by reshma-r-p** [comment]
ok..Thanks.
Can i expct that by end of this month?
